// Generated by gencpp from file roboboat/BoatHealth.msg
// DO NOT EDIT!


#ifndef ROBOBOAT_MESSAGE_BOATHEALTH_H
#define ROBOBOAT_MESSAGE_BOATHEALTH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace roboboat
{
template <class ContainerAllocator>
struct BoatHealth_
{
  typedef BoatHealth_<ContainerAllocator> Type;

  BoatHealth_()
    : header()
    , temp_l(0.0)
    , temp_r(0.0)
    , batt_p(0.0)
    , batt_l(0.0)
    , batt_r(0.0)
    , water_l(false)
    , water_m(false)
    , water_r(false)  {
    }
  BoatHealth_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , temp_l(0.0)
    , temp_r(0.0)
    , batt_p(0.0)
    , batt_l(0.0)
    , batt_r(0.0)
    , water_l(false)
    , water_m(false)
    , water_r(false)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _temp_l_type;
  _temp_l_type temp_l;

   typedef float _temp_r_type;
  _temp_r_type temp_r;

   typedef float _batt_p_type;
  _batt_p_type batt_p;

   typedef float _batt_l_type;
  _batt_l_type batt_l;

   typedef float _batt_r_type;
  _batt_r_type batt_r;

   typedef uint8_t _water_l_type;
  _water_l_type water_l;

   typedef uint8_t _water_m_type;
  _water_m_type water_m;

   typedef uint8_t _water_r_type;
  _water_r_type water_r;




  typedef boost::shared_ptr< ::roboboat::BoatHealth_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboboat::BoatHealth_<ContainerAllocator> const> ConstPtr;

}; // struct BoatHealth_

typedef ::roboboat::BoatHealth_<std::allocator<void> > BoatHealth;

typedef boost::shared_ptr< ::roboboat::BoatHealth > BoatHealthPtr;
typedef boost::shared_ptr< ::roboboat::BoatHealth const> BoatHealthConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboboat::BoatHealth_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboboat::BoatHealth_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboboat

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'roboboat': ['/home/boat-team/catkin_ws/src/roboboat/msg'], 'nmea_msgs': ['/opt/ros/jade/share/nmea_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboboat::BoatHealth_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboboat::BoatHealth_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboboat::BoatHealth_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboboat::BoatHealth_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboboat::BoatHealth_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboboat::BoatHealth_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboboat::BoatHealth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "99250fac6bf2b1f4a6ceeb24cfdc8ed9";
  }

  static const char* value(const ::roboboat::BoatHealth_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x99250fac6bf2b1f4ULL;
  static const uint64_t static_value2 = 0xa6ceeb24cfdc8ed9ULL;
};

template<class ContainerAllocator>
struct DataType< ::roboboat::BoatHealth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboboat/BoatHealth";
  }

  static const char* value(const ::roboboat::BoatHealth_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboboat::BoatHealth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
# Left Motor Controller Temperature\n\
float32 temp_l\n\
\n\
# Right Motor Controller Temperature\n\
float32 temp_r\n\
\n\
# Primary Battery Voltage\n\
float32 batt_p\n\
\n\
# Left Motor Battery Voltage\n\
float32 batt_l\n\
\n\
# Right Motor Battery Voltage\n\
float32 batt_r\n\
\n\
# Left Hull Water Sensor\n\
bool    water_l\n\
\n\
# Main Hull Water Sensor\n\
bool    water_m\n\
\n\
# Right Hull Water Sensor\n\
bool    water_r\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::roboboat::BoatHealth_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboboat::BoatHealth_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.temp_l);
      stream.next(m.temp_r);
      stream.next(m.batt_p);
      stream.next(m.batt_l);
      stream.next(m.batt_r);
      stream.next(m.water_l);
      stream.next(m.water_m);
      stream.next(m.water_r);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct BoatHealth_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboboat::BoatHealth_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboboat::BoatHealth_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "temp_l: ";
    Printer<float>::stream(s, indent + "  ", v.temp_l);
    s << indent << "temp_r: ";
    Printer<float>::stream(s, indent + "  ", v.temp_r);
    s << indent << "batt_p: ";
    Printer<float>::stream(s, indent + "  ", v.batt_p);
    s << indent << "batt_l: ";
    Printer<float>::stream(s, indent + "  ", v.batt_l);
    s << indent << "batt_r: ";
    Printer<float>::stream(s, indent + "  ", v.batt_r);
    s << indent << "water_l: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.water_l);
    s << indent << "water_m: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.water_m);
    s << indent << "water_r: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.water_r);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOBOAT_MESSAGE_BOATHEALTH_H
