// Generated by gencpp from file roboboat/MotorControl.msg
// DO NOT EDIT!


#ifndef ROBOBOAT_MESSAGE_MOTORCONTROL_H
#define ROBOBOAT_MESSAGE_MOTORCONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace roboboat
{
template <class ContainerAllocator>
struct MotorControl_
{
  typedef MotorControl_<ContainerAllocator> Type;

  MotorControl_()
    : header()
    , left_motor(0)
    , right_motor(0)  {
    }
  MotorControl_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left_motor(0)
    , right_motor(0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint16_t _left_motor_type;
  _left_motor_type left_motor;

   typedef uint16_t _right_motor_type;
  _right_motor_type right_motor;




  typedef boost::shared_ptr< ::roboboat::MotorControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboboat::MotorControl_<ContainerAllocator> const> ConstPtr;

}; // struct MotorControl_

typedef ::roboboat::MotorControl_<std::allocator<void> > MotorControl;

typedef boost::shared_ptr< ::roboboat::MotorControl > MotorControlPtr;
typedef boost::shared_ptr< ::roboboat::MotorControl const> MotorControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboboat::MotorControl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboboat::MotorControl_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboboat

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'roboboat': ['/home/boat-team/catkin_ws/src/roboboat/msg'], 'nmea_msgs': ['/opt/ros/jade/share/nmea_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboboat::MotorControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboboat::MotorControl_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboboat::MotorControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboboat::MotorControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboboat::MotorControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboboat::MotorControl_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboboat::MotorControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4ce58821abb7342cd0cee3d9424cf458";
  }

  static const char* value(const ::roboboat::MotorControl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4ce58821abb7342cULL;
  static const uint64_t static_value2 = 0xd0cee3d9424cf458ULL;
};

template<class ContainerAllocator>
struct DataType< ::roboboat::MotorControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboboat/MotorControl";
  }

  static const char* value(const ::roboboat::MotorControl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboboat::MotorControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
# Left Motor Control Pulse Width\n\
uint16 left_motor\n\
\n\
# Right Motor Control Pulse Width\n\
uint16 right_motor\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::roboboat::MotorControl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboboat::MotorControl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left_motor);
      stream.next(m.right_motor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MotorControl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboboat::MotorControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboboat::MotorControl_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left_motor: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.left_motor);
    s << indent << "right_motor: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.right_motor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOBOAT_MESSAGE_MOTORCONTROL_H
