// Generated by gencpp from file roboboat/RelayControl.msg
// DO NOT EDIT!


#ifndef ROBOBOAT_MESSAGE_RELAYCONTROL_H
#define ROBOBOAT_MESSAGE_RELAYCONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace roboboat
{
template <class ContainerAllocator>
struct RelayControl_
{
  typedef RelayControl_<ContainerAllocator> Type;

  RelayControl_()
    : header()
    , motor(false)
    , pump(false)  {
    }
  RelayControl_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , motor(false)
    , pump(false)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _motor_type;
  _motor_type motor;

   typedef uint8_t _pump_type;
  _pump_type pump;




  typedef boost::shared_ptr< ::roboboat::RelayControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboboat::RelayControl_<ContainerAllocator> const> ConstPtr;

}; // struct RelayControl_

typedef ::roboboat::RelayControl_<std::allocator<void> > RelayControl;

typedef boost::shared_ptr< ::roboboat::RelayControl > RelayControlPtr;
typedef boost::shared_ptr< ::roboboat::RelayControl const> RelayControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboboat::RelayControl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboboat::RelayControl_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboboat

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'roboboat': ['/home/boat-team/catkin_ws/src/roboboat/msg'], 'nmea_msgs': ['/opt/ros/jade/share/nmea_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboboat::RelayControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboboat::RelayControl_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboboat::RelayControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboboat::RelayControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboboat::RelayControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboboat::RelayControl_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboboat::RelayControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d861d440ba0170c43fedaf3385911c0c";
  }

  static const char* value(const ::roboboat::RelayControl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd861d440ba0170c4ULL;
  static const uint64_t static_value2 = 0x3fedaf3385911c0cULL;
};

template<class ContainerAllocator>
struct DataType< ::roboboat::RelayControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboboat/RelayControl";
  }

  static const char* value(const ::roboboat::RelayControl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboboat::RelayControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
# Motor Power Relays\n\
bool motor\n\
\n\
# Pump Power Relays\n\
bool pump\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::roboboat::RelayControl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboboat::RelayControl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.motor);
      stream.next(m.pump);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct RelayControl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboboat::RelayControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboboat::RelayControl_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "motor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.motor);
    s << indent << "pump: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pump);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOBOAT_MESSAGE_RELAYCONTROL_H
